name: notifications_handler_demo
description: Demo project for the package firebase_notifications_handler on pub.dev

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.1.0
  easy_container: ^1.0.4
  firebase_notifications_handler:
    path: "../"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
