name: firebase_notifications_handler
description: Simple notifications handler which provides callbacks like onTap which really make it easy to handle notification taps and a lot more.
version: 1.1.0
homepage: https://github.com/rithik-dev/firebase_notifications_handler

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.5
  path_provider: ^2.0.11
  firebase_messaging: ^14.0.2
  flutter_local_notifications: ^12.0.2

dev_dependencies:
  flutter_lints: ^2.0.1

false_secrets:
  - /example/android/app/google-services.json
  - /example/lib/firebase_options.dart